// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: v2ovbRJGsEFmRX1j8f3Jsa
// Component: yQ0djKSUNO
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: HBT3Um4xFJ/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: v2ovbRJGsEFmRX1j8f3Jsa/projectcss
import * as sty from "./PlasmicHome.module.css"; // plasmic-import: yQ0djKSUNO/css
import GoogleIconIcon from "../gamer_groups/icons/PlasmicIcon__GoogleIcon"; // plasmic-import: LIzhrbm1R/icon

export const PlasmicHome__VariantProps = new Array();

export const PlasmicHome__ArgProps = new Array();

function PlasmicHome__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <div className={classNames(defaultcss.all, sty.freeBox__hspjS)}>
            <div className={classNames(defaultcss.all, sty.freeBox__nN0Gp)}>
              <div className={classNames(defaultcss.all, sty.freeBox__h7IMg)}>
                <span
                  className={classNames(
                    defaultcss.span,
                    defaultcss.__wab_text,
                    sty.span___5Ysnw
                  )}
                >
                  {"Gamer"}
                </span>

                <span
                  className={classNames(
                    defaultcss.span,
                    defaultcss.__wab_text,
                    sty.span___10QhE
                  )}
                >
                  {"Groups"}
                </span>

                <div
                  className={classNames(defaultcss.all, sty.freeBox___0FVhh)}
                >
                  <span
                    className={classNames(
                      defaultcss.span,
                      defaultcss.__wab_text,
                      sty.span__oXhwV
                    )}
                  >
                    {"Find a"}
                  </span>

                  <span
                    className={classNames(
                      defaultcss.span,
                      defaultcss.__wab_text,
                      sty.span__ii4H0
                    )}
                  >
                    {" team"}
                  </span>

                  <span
                    className={classNames(
                      defaultcss.span,
                      defaultcss.__wab_text,
                      sty.span__xsy57
                    )}
                  >
                    {", more like "}
                  </span>

                  <span
                    className={classNames(
                      defaultcss.span,
                      defaultcss.__wab_text,
                      sty.span___1JcKk
                    )}
                  >
                    {"you"}
                  </span>

                  <span
                    className={classNames(
                      defaultcss.span,
                      defaultcss.__wab_text,
                      sty.span__nPn9L
                    )}
                  >
                    {"."}
                  </span>
                </div>
              </div>

              <div className={classNames(defaultcss.all, sty.freeBox__ofkCa)}>
                <div className={classNames(defaultcss.all, sty.freeBox__luc3N)}>
                  <div
                    className={classNames(defaultcss.all, sty.freeBox__s3MCi)}
                  >
                    <input
                      className={classNames(
                        defaultcss.input,
                        sty.textbox___2UsBr
                      )}
                      placeholder={"EMAIL"}
                      size={1}
                      type={"text"}
                      value={""}
                    />

                    <input
                      className={classNames(
                        defaultcss.input,
                        sty.textbox__hFFwf
                      )}
                      placeholder={"VERIFY EMAIL"}
                      size={1}
                      type={"text"}
                      value={""}
                    />

                    <input
                      className={classNames(
                        defaultcss.input,
                        sty.textbox___1TvzJ
                      )}
                      placeholder={"USERNAME"}
                      size={1}
                      type={"text"}
                      value={""}
                    />

                    <input
                      className={classNames(
                        defaultcss.input,
                        sty.textbox___2LTq9
                      )}
                      placeholder={"PASSWORD"}
                      size={1}
                      type={"text"}
                      value={""}
                    />

                    <button
                      className={classNames(
                        defaultcss.button,
                        defaultcss.__wab_text,
                        sty.button__jjDJ
                      )}
                    >
                      {"REGISTER"}
                    </button>
                  </div>
                </div>

                <div className={classNames(defaultcss.all, sty.freeBox__d0Foe)}>
                  <GoogleIconIcon
                    data-plasmic-name={"svg"}
                    data-plasmic-override={overrides.svg}
                    className={classNames(defaultcss.all, sty.svg)}
                    role={"img"}
                  />

                  <button
                    className={classNames(
                      defaultcss.button,
                      defaultcss.__wab_text,
                      sty.button__zsUt7
                    )}
                  >
                    {"Sign in with Google"}
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: ["root", "svg"],
  svg: ["svg"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHome__ArgProps,
      internalVariantPropNames: PlasmicHome__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHome__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHome";
  } else {
    func.displayName = `PlasmicHome.${nodeName}`;
  }
  return func;
}

export const PlasmicHome = Object.assign(
  // Top-level PlasmicHome renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    // Metadata about props expected for PlasmicHome
    internalVariantProps: PlasmicHome__VariantProps,
    internalArgProps: PlasmicHome__ArgProps
  }
);

export default PlasmicHome;
/* prettier-ignore-end */
